// English topics. Original US boards plus jovial, India-flavoured ones for Andhra and Telangana students.
// difficulty: common = 1 pt, medium = 2 pts, obscure = 3 pts (the less obvious, funnier answers).
// Boards are meant to be fun and relatable, not a knowledge test.

const t = (text, difficulty, aliases = [], gloss = '') => ({ key: text, text, difficulty, aliases, gloss });

export default [
  {
    id: 'nye-party', locale: 'en-US',
    prompt: "Things you'd find at a New Year's Eve party",
    answers: [
      t('Champagne', 'common', ['bubbly', 'sparkling wine', 'prosecco', 'cava']),
      t('Fireworks', 'common', ['firecrackers', 'pyrotechnics']),
      t('Countdown', 'common', ['counting down', 'ten nine eight']),
      t('Confetti', 'common', ['streamers']),
      t('Midnight kiss', 'medium', ["new year's kiss", 'kiss at midnight']),
      t('Ball drop', 'medium', ['times square ball', 'dropping the ball']),
      t('Noisemakers', 'medium', ['party horns', 'horns', 'kazoos', 'party blowers']),
      t('Resolutions', 'medium', ["new year's resolutions", 'goals for the year']),
      t('Party hats', 'medium', ['paper hats', 'tiaras', 'crowns']),
      t('Auld Lang Syne', 'obscure', ['the new year song', 'should old acquaintance']),
      t('Sparklers', 'obscure'),
      t('Twelve grapes', 'obscure', ['lucky grapes', 'eating grapes at midnight']),
    ],
  },
  {
    id: 'kitchen', locale: 'en-US',
    prompt: 'Things in a kitchen',
    answers: [
      t('Refrigerator', 'common', ['fridge', 'freezer']),
      t('Stove', 'common', ['oven', 'range', 'cooktop', 'burners']),
      t('Sink', 'common', ['faucet', 'tap']),
      t('Microwave', 'common'),
      t('Dishwasher', 'medium'),
      t('Toaster', 'medium', ['toaster oven']),
      t('Cutting board', 'medium', ['chopping board']),
      t('Knife block', 'medium', ['knives', "chef's knife"]),
      t('Spatula', 'medium', ['flipper', 'turner']),
      t('Colander', 'obscure', ['strainer', 'sieve']),
      t('Spice rack', 'obscure', ['spices', 'seasonings']),
      t('Oven mitts', 'obscure', ['pot holders', 'oven gloves']),
    ],
  },
  {
    id: 'beach-day', locale: 'en-US',
    prompt: 'Things you bring or see on a beach day',
    answers: [
      t('Sunscreen', 'common', ['sunblock', 'spf', 'suntan lotion']),
      t('Towel', 'common', ['beach towel']),
      t('Umbrella', 'common', ['parasol', 'beach umbrella']),
      t('Sunglasses', 'common', ['shades']),
      t('Swimsuit', 'medium', ['bathing suit', 'swim trunks', 'bikini']),
      t('Cooler', 'medium', ['ice chest']),
      t('Sandcastle', 'medium', ['sand castle', 'bucket and spade']),
      t('Flip-flops', 'medium', ['sandals']),
      t('Frisbee', 'medium', ['flying disc']),
      t('Seashells', 'obscure', ['shells']),
      t('Boogie board', 'obscure', ['bodyboard']),
      t('Lifeguard', 'obscure', ['lifeguard tower']),
    ],
  },
  {
    id: 'late-for-work', locale: 'en-US',
    prompt: 'Reasons you were late for work',
    answers: [
      t('Traffic', 'common', ['traffic jam', 'rush hour']),
      t('Overslept', 'common', ['slept in', "alarm didn't go off", 'hit snooze']),
      t('Car trouble', 'common', ['flat tire', "car wouldn't start", 'dead battery']),
      t('Train or bus delay', 'medium', ['missed the bus', 'train was late', 'public transport']),
      t('Kids', 'medium', ['school drop-off', 'the kids']),
      t('Lost keys', 'medium', ["couldn't find my keys", 'keys']),
      t('Bad weather', 'medium', ['snow', 'rain', 'storm']),
      t('Coffee run', 'obscure', ['coffee line', 'getting coffee']),
      t('Appointment', 'obscure', ['doctor', 'dentist']),
      t('Pet emergency', 'obscure', ['the dog', 'vet']),
    ],
  },

  {
    id: 'homework-excuses', locale: 'en-US',
    prompt: 'Excuses for not doing your homework',
    answers: [
      t('I forgot', 'common', ['forgot', 'totally forgot', 'i completely forgot']),
      t('Left it at home', 'common', ['left my notebook at home', 'notebook is at home', 'its at home']),
      t('Power cut', 'common', ['no current', 'no electricity', 'current went', 'power went off']),
      t('I was sick', 'common', ['fever', 'sick', 'headache', 'stomach ache', 'not well']),
      t('The dog ate it', 'medium', ['dog ate my homework', 'my dog ate it', 'dog']),
      t('Relatives came home', 'medium', ['guests came', 'relatives', 'guests', 'cousins came']),
      t('Went to a wedding', 'medium', ['wedding', 'function', 'marriage function']),
      t('Little brother tore it', 'medium', ['my brother tore it', 'sister tore it', 'baby tore it', 'tore it']),
      t("Didn't know there was homework", 'medium', ["didn't know", 'nobody told me', 'no one told me']),
      t('Fell asleep', 'medium', ['slept', 'slept early', 'i fell asleep']),
      t('Watching the cricket match', 'obscure', ['cricket match', 'ipl', 'watching cricket', 'the match']),
      t('It got wet in the rain', 'obscure', ['got wet', 'rain', 'wet in the rain']),
      t('Did it but forgot to bring it', 'obscure', ['i did it', 'did it at home', 'i did it but']),
    ],
  },
  {
    id: 'power-cut', locale: 'en-US',
    prompt: 'Things you do when the power goes off',
    answers: [
      t('Light a candle', 'common', ['candle', 'candles']),
      t('Phone torch', 'common', ['torch', 'flashlight', 'phone light']),
      t('Mosquitoes biting', 'common', ['mosquitoes', 'mosquito', 'mosquito bites']),
      t('Sweating', 'common', ['sweat', 'sweaty', 'too hot']),
      t('Fan yourself', 'medium', ['hand fan', 'fan', 'fanning', 'fan with a book']),
      t('Sit on the terrace', 'medium', ['terrace', 'go outside', 'balcony', 'sit outside']),
      t('Call the electricity office', 'medium', ['complaint', 'call the lineman', 'eb office', 'electricity office']),
      t('Inverter', 'medium', ['ups', 'generator']),
      t('Worry about phone battery', 'medium', ['phone battery', 'charging', 'battery low', 'power bank']),
      t('Antakshari', 'medium', ['singing', 'sing songs', 'songs']),
      t('Go to sleep', 'medium', ['sleep', 'sleeping', 'nap']),
      t('Ghost stories', 'obscure', ['ghost story', 'scary stories', 'horror stories']),
      t('Check if the neighbours have power', 'obscure', ['neighbours', 'check the neighbours', 'neighbour house']),
    ],
  },
  {
    id: 'mom-says', locale: 'en-US',
    prompt: 'Things moms always say',
    answers: [
      t('Go and study', 'common', ['study', 'study now', 'go study', 'read your books']),
      t('Put the phone down', 'common', ['phone', 'keep the phone away', 'stop using the phone', 'too much phone']),
      t('Did you eat?', 'common', ['have you eaten', 'eat', 'eat something']),
      t("Wake up, it's late", 'common', ['wake up', 'get up', 'its late', 'you are late']),
      t('Be careful', 'common', ['careful', 'take care', 'be safe']),
      t("Look at the neighbour's kid", 'medium', ['neighbour kid', "neighbour's son", "neighbour's daughter", 'sharma ji ka beta', 'comparing']),
      t('Switch off the TV', 'medium', ['tv off', 'turn off the tv', 'stop watching tv', 'tv']),
      t('Clean your room', 'medium', ['clean room', 'room', 'tidy up']),
      t("I'll tell your father", 'medium', ['tell dad', 'wait till dad comes', 'dad']),
      t('Drink water', 'obscure', ['water', 'drink more water']),
      t('Who are you talking to?', 'obscure', ['who is that', 'who are you chatting with', 'who is it']),
      t('Wear a sweater', 'obscure', ['sweater', 'its cold', 'jacket']),
      t("Don't play in the sun", 'obscure', ['sun', 'come inside', 'too hot outside']),
    ],
  },
  {
    id: 'gully-cricket', locale: 'en-US',
    prompt: 'Things that happen in gully cricket',
    answers: [
      t('Bat', 'common', ['cricket bat', 'plastic bat']),
      t('Tennis ball', 'common', ['ball', 'rubber ball']),
      t('Bricks as stumps', 'common', ['bricks', 'stumps', 'wickets', 'stones as wickets']),
      t('Broken window', 'common', ['window broke', 'glass broke', 'broke the glass', 'window']),
      t("I'm not out!", 'common', ['not out', 'i am not out', 'fight', 'argument']),
      t("Ball lost in the neighbour's house", 'medium', ['lost ball', 'ball lost', 'ball went over the wall', 'neighbour house']),
      t('One tip one hand', 'medium', ['one bounce catch', 'one tip catch', 'one hand catch']),
      t('Trial ball', 'medium', ['trial', 'practice ball']),
      t('Bat owner is captain', 'medium', ['bat owner', 'whose bat', 'captain', 'owner bats first']),
      t('Mom calling you home', 'medium', ['mom calling', 'amma calling', 'come home', 'dinner time']),
      t('Street dogs', 'obscure', ['dogs', 'dog chasing', 'dog']),
      t('Too dark to see', 'obscure', ['dark', 'its dark', 'getting dark']),
      t('Last man batting', 'obscure', ['last man', 'one man batting', 'last man stands']),
    ],
  },
  {
    id: 'midnight-snacks', locale: 'en-US',
    prompt: "Midnight snacks when you're hungry",
    answers: [
      t('Maggi', 'common', ['noodles', 'instant noodles', 'maggi noodles']),
      t('Biscuits', 'common', ['biscuit', 'parle g', 'cookies', 'marie']),
      t('Chips', 'common', ['lays', 'kurkure', 'crisps']),
      t('Curd rice', 'common', ['curd', 'perugu annam', 'yogurt rice']),
      t('Pickle rice', 'medium', ['pickle', 'avakaya', 'avakaya rice', 'mango pickle']),
      t('Omelette', 'medium', ['egg', 'eggs', 'omlet']),
      t('Leftover biryani', 'medium', ['biryani', 'leftovers']),
      t('Ice cream', 'medium', ['icecream', 'kulfi']),
      t('Chocolate', 'medium', ['chocolates', 'dairy milk', 'kitkat']),
      t('Order online', 'medium', ['swiggy', 'zomato', 'food delivery', 'order food']),
      t('Sweets from the box', 'obscure', ['sweets', 'sweet box', 'laddu', 'hidden sweets']),
      t('Peanuts', 'obscure', ['groundnuts', 'mixture']),
      t('Banana', 'obscure', ['bananas', 'fruit']),
    ],
  },
  {
    id: 'birthday-party', locale: 'en-US',
    prompt: 'Things at a birthday party',
    answers: [
      t('Cake', 'common', ['birthday cake']),
      t('Candles', 'common', ['candle']),
      t('Balloons', 'common', ['balloon']),
      t('Gifts', 'common', ['presents', 'gift', 'present']),
      t('Friends', 'common', ['guests', 'classmates']),
      t('Birthday song', 'medium', ['happy birthday song', 'happy birthday']),
      t('Party hats', 'medium', ['caps', 'birthday cap', 'party cap']),
      t('Return gifts', 'medium', ['return gift']),
      t('Chocolates', 'medium', ['chocolate', 'toffees']),
      t('Decorations', 'medium', ['streamers', 'ribbons', 'decoration']),
      t('Games', 'medium', ['party games', 'musical chairs']),
      t('Cake on the face', 'obscure', ['cake smash', 'cake on face', 'face full of cake']),
      t('Photos', 'obscure', ['camera', 'selfies', 'photographs']),
    ],
  },
  {
    id: 'monsoon', locale: 'en-US',
    prompt: 'Things you see in the monsoon',
    answers: [
      t('Umbrella', 'common', ['umbrellas']),
      t('Raincoat', 'common', ['rain coat']),
      t('Puddles', 'common', ['puddle', 'mud', 'muddy water']),
      t('Paper boats', 'medium', ['paper boat']),
      t('Thunder', 'medium'),
      t('Lightning', 'medium', ['lighting']),
      t('Frogs', 'medium', ['frog']),
      t('Rainbow', 'medium'),
      t('Dark clouds', 'medium', ['clouds', 'cloud']),
      t('Hot bajji', 'obscure', ['bajji', 'pakoda', 'pakora', 'mirchi bajji', 'pakodi']),
      t('Roasted corn', 'obscure', ['bhutta', 'corn']),
      t('Rain holiday', 'obscure', ['holiday', 'school holiday']),
      t('Cold and cough', 'obscure', ['cold', 'cough', 'sneezing']),
    ],
  },
  {
    id: 'street-food', locale: 'en-US',
    prompt: 'Street food you can never say no to',
    answers: [
      t('Pani puri', 'common', ['gol gappa', 'golgappa', 'puchka', 'gupchup', 'pani poori']),
      t('Samosa', 'common', ['samosas']),
      t('Mirchi bajji', 'common', ['bajji', 'mirchi bhaji', 'chilli bajji']),
      t('Pav bhaji', 'common'),
      t('Bhel puri', 'medium', ['bhel', 'churumuri']),
      t('Chaat', 'medium', ['dahi puri', 'papdi chaat', 'masala puri']),
      t('Vada pav', 'medium', ['vada pao']),
      t('Momos', 'medium', ['momo']),
      t('Jalebi', 'medium', ['jilebi', 'jalebis']),
      t('Roasted corn', 'medium', ['bhutta', 'corn', 'corn on the cob']),
      t('Kulfi', 'obscure', ['ice cream', 'kulfi ice']),
      t('Sugarcane juice', 'obscure', ['ganne ka juice', 'cheruku rasam']),
      t('Egg puffs', 'obscure', ['puffs', 'egg puff', 'veg puff', 'bakery puffs']),
    ],
  },
];
