// English topics.
// style:'contextual'  — answers are situations/behaviours/feelings; players describe them
//                       rather than naming them directly, so Jev does real semantic work.
// style:'classic'     — traditional category-listing boards; local exact/alias matching
//                       handles most guesses; good for a quick no-frills round.

const t = (text, difficulty, aliases = [], gloss = '') => ({ key: text, text, difficulty, aliases, gloss });

// ─── Contextual boards (Jev showcase) ────────────────────────────────────────

const contextual = [
  {
    id: 'phone-stress', locale: 'en-US', style: 'contextual',
    prompt: 'Things about your phone that stress you out',
    answers: [
      t('Battery at 1%', 'common', ['one percent', 'low battery', 'dying battery', 'battery warning']),
      t('Forgot to reply someone', 'common', ['unread message', 'left on read', 'unseen texts', 'pending replies']),
      t('Storage full', 'common', ['no space', 'phone full', 'cannot take photo', 'storage alert']),
      t('Cracked screen', 'common', ['broken screen', 'shattered glass', 'screen smashed']),
      t('Buffering', 'medium', ['slow internet', 'loading forever', 'spinning circle', 'video stuck']),
      t('Autocorrect sending the wrong word', 'medium', ['autocorrect fail', 'wrong word sent', 'embarrassing text']),
      t('Group chat you cannot leave', 'medium', ['stuck in group', 'muted group', 'group chat noise']),
      t('Phone overheating', 'medium', ['too hot', 'phone burning', 'overheating']),
      t('Face ID not recognising you', 'obscure', ['face unlock failing', 'biometric fail', 'wont scan']),
      t('Dropping it face-down', 'obscure', ['face down drop', 'screen drop', 'horror of dropping it']),
      t('Software update you keep postponing', 'obscure', ['update reminder', 'remind me later', 'that update popup']),
    ],
  },
  {
    id: 'family-whatsapp', locale: 'en-US', style: 'contextual',
    prompt: 'Things you find on a family WhatsApp group',
    answers: [
      t('Good morning message with flowers', 'common', ['morning flowers', 'good morning gif', 'morning wishes']),
      t('Forwarded fake news', 'common', ['is this true message', 'fake news forward', 'unverified forward']),
      t('Birthday edited photo', 'common', ['birthday collage', 'birthday poster', 'birthday sticker image']),
      t('Message sent to the wrong group', 'medium', ['wrong chat', 'accidental message', 'oops wrong group']),
      t('Religious forward with a share request', 'medium', ['share this to ten people', 'blessings message', 'chain message']),
      t('Marriage match suggestion', 'medium', ['alliance message', 'proposal talks', 'match for someone']),
      t('Elder using the wrong emoji', 'medium', ['emoji misuse', 'wrong emoji', 'emoji confusion']),
      t('Surprise video call announcing big news', 'medium', ['unexpected family call', 'video call news']),
      t('Dad jokes nobody asked for', 'obscure', ['uncle jokes', 'corny joke', 'dad pun']),
      t('Same old forward sent again', 'obscure', ['already seen this', 'repeated forward', 'that same joke again']),
    ],
  },
  {
    id: 'feels-forever', locale: 'en-US', style: 'contextual',
    prompt: 'Things that feel like they take forever',
    answers: [
      t('Last five minutes of school', 'common', ['clock watching', 'waiting for the bell', 'end of school day']),
      t('Buffering video', 'common', ['loading screen', 'spinning circle', 'video stuck']),
      t('Phone charging from 1%', 'common', ['slow charge', 'charging from dead', 'one percent to ten']),
      t('Waiting for a food delivery', 'common', ['order still on the way', 'delivery late', 'swiggy taking long']),
      t('Doctor waiting room', 'medium', ['hospital queue', 'appointment overdue', 'sitting in clinic']),
      t('Waiting for a reply from someone you like', 'medium', ['seen but no reply', 'blue ticks silence', 'waiting for text back']),
      t('Download stuck at 99%', 'medium', ['almost downloaded', 'last percent forever', 'stuck at the end']),
      t('Unskippable ad before a video', 'medium', ['forced ad', 'countdown to skip', 'ad playing']),
      t('Counting pressure cooker whistles', 'obscure', ['waiting for the last whistle', 'whistle count', 'cooker whistle']),
      t('Microwave last ten seconds', 'obscure', ['staring at the timer', 'microwave countdown', 'final ten seconds']),
    ],
  },
  {
    id: 'homework-excuses', locale: 'en-US', style: 'contextual',
    prompt: 'Excuses for not doing your homework',
    answers: [
      t('I forgot', 'common', ['forgot', 'totally forgot', 'completely forgot']),
      t('Left it at home', 'common', ['notebook at home', 'left my book at home']),
      t('Power cut', 'common', ['no electricity', 'current went', 'no current']),
      t('I was sick', 'common', ['fever', 'not feeling well', 'headache', 'stomach ache']),
      t('The dog ate it', 'medium', ['dog ate my homework', 'dog destroyed it']),
      t('Relatives came home', 'medium', ['guests came', 'cousins visited', 'family came over']),
      t('Went to a wedding', 'medium', ['function', 'marriage function', 'attended a wedding']),
      t('Little sibling tore it', 'medium', ['brother tore it', 'baby destroyed it', 'sister tore it']),
      t("Didn't know there was homework", 'medium', ['nobody told me', 'no one told me', "didn't know"]),
      t('Fell asleep', 'medium', ['slept', 'slept early', 'dozed off']),
      t('Was watching the cricket match', 'obscure', ['ipl', 'cricket match', 'match was on']),
      t('It got wet in the rain', 'obscure', ['rained on it', 'book got wet', 'wet in the rain']),
      t('Did it but forgot to bring it', 'obscure', ['did it at home', 'left completed homework behind']),
    ],
  },
  {
    id: 'power-cut', locale: 'en-US', style: 'contextual',
    prompt: 'Things you do when the power goes off',
    answers: [
      t('Light a candle', 'common', ['candle', 'candles', 'lighting candles']),
      t('Phone torch', 'common', ['torch', 'flashlight', 'phone light']),
      t('Mosquitoes biting', 'common', ['mosquitoes', 'mosquito bites']),
      t('Sweating in the heat', 'common', ['sweat', 'too hot', 'sweaty']),
      t('Fan yourself with a book', 'medium', ['hand fan', 'fanning yourself', 'hand fan or book']),
      t('Sit on the terrace', 'medium', ['go to the terrace', 'sit outside', 'balcony', 'go outside']),
      t('Call the electricity office', 'medium', ['complaint call', 'call the lineman', 'eb office']),
      t('Inverter kicks in', 'medium', ['ups', 'generator', 'inverter']),
      t('Worry about phone battery', 'medium', ['low battery panic', 'power bank', 'charging anxiety']),
      t('Antakshari', 'medium', ['singing songs', 'songs', 'sing together']),
      t('Go to sleep', 'medium', ['sleep', 'nap', 'sleeping']),
      t('Tell ghost stories', 'obscure', ['scary stories', 'horror stories', 'ghost story']),
      t("Check if the neighbours have power", 'obscure', ['neighbour house light', 'look at neighbours', 'neighbours got power']),
    ],
  },
  {
    id: 'mom-says', locale: 'en-US', style: 'contextual',
    prompt: 'Things moms always say',
    answers: [
      t('Go and study', 'common', ['study', 'go study', 'read your books', 'study now']),
      t('Put the phone down', 'common', ['keep the phone away', 'stop using the phone', 'too much phone']),
      t('Did you eat?', 'common', ['have you eaten', 'eat something', 'go eat']),
      t("Wake up, it's late", 'common', ['wake up', 'get up', 'its late', 'you will be late']),
      t('Be careful', 'common', ['careful', 'take care', 'be safe']),
      t("Look at the neighbour's kid", 'medium', ['neighbour kid comparison', "neighbour's son", 'comparing me to someone']),
      t('Switch off the TV', 'medium', ['turn off the tv', 'stop watching tv', 'tv off']),
      t('Clean your room', 'medium', ['tidy up', 'clean room', 'your room is a mess']),
      t("I'll tell your father", 'medium', ['wait till dad comes', 'tell dad', 'father will hear about this']),
      t('Drink water', 'obscure', ['drink more water', 'have some water']),
      t('Who are you talking to?', 'obscure', ['who are you chatting with', 'who is that', 'who is calling']),
      t('Wear a sweater', 'obscure', ['its cold', 'jacket', 'sweater']),
      t("Don't play in the sun", 'obscure', ['come inside', 'too hot outside', 'stay out of the sun']),
    ],
  },
  {
    id: 'wont-admit', locale: 'en-US', style: 'contextual',
    prompt: 'Things everyone does but will never admit',
    answers: [
      t('Sniff food to check if it has gone bad', 'common', ['smell the leftovers', 'sniff test food']),
      t('Talk to yourself out loud', 'common', ['monologue at home', 'muttering to yourself', 'self-talk']),
      t('Fake a phone call to avoid someone', 'common', ['pretend phone call', 'act busy on the phone']),
      t("Stalk someone's old Instagram photos", 'medium', ['scroll back years on instagram', 'instagram stalk']),
      t('Sing at the top of your voice when home alone', 'medium', ['sing when nobody is watching', 'home karaoke']),
      t('Pretend to sleep to avoid a conversation', 'medium', ['fake sleeping', 'pretend to be asleep']),
      t('Check your phone again two seconds after putting it down', 'medium', ['instantly pick phone back up', 'check phone immediately']),
      t('Eat food that fell on the floor', 'medium', ['five second rule', 'floor food', 'dropped food']),
      t('Check your own breath or smell', 'obscure', ['breathe into hand', 'armpit sniff', 'smell check']),
      t('Read old conversations when missing someone', 'obscure', ['old chats', 'going through old texts']),
      t('Lie about being five minutes away', 'obscure', ['say five minutes but not ready', 'almost there lie']),
    ],
  },
  {
    id: 'gully-cricket', locale: 'en-US', style: 'contextual',
    prompt: 'Things that happen in gully cricket',
    answers: [
      t('Plastic bat', 'common', ['bat', 'cricket bat', 'the bat']),
      t('Tennis ball', 'common', ['ball', 'rubber ball', 'tape ball']),
      t('Bricks for stumps', 'common', ['bricks as wickets', 'stones for stumps', 'make-shift stumps']),
      t("Breaking someone's window", 'common', ['window broke', 'glass shattered', 'ball hit the window']),
      t("I'm not out!", 'common', ['not out argument', 'claiming not out', 'fight about out']),
      t("Ball in the neighbour's compound", 'medium', ['ball went over the wall', 'lost ball next door', 'ball in neighbour house']),
      t('One tip one hand rule', 'medium', ['one bounce catch', 'one hand catch off the pitch', 'tip catch']),
      t('Trial ball', 'medium', ['the warm-up ball', 'practice throw', 'trial throw']),
      t('Whoever owns the bat is captain', 'medium', ['bat owner decides', 'bat owner bats first', 'bat holder is captain']),
      t('Mom calling you home', 'medium', ['amma calling', 'parent calling you back', 'dinner call']),
      t('Street dog chasing the ball', 'obscure', ['dog runs off with ball', 'stray dog', 'dog joins the game']),
      t('Too dark to see', 'obscure', ['getting dark', 'lights out', 'playing in the dark']),
      t('Last man batting alone', 'obscure', ['last person batting', 'one man left', 'last man stands']),
    ],
  },
  {
    id: 'midnight-snacks', locale: 'en-US', style: 'contextual',
    prompt: "Midnight snacks when you're suddenly hungry",
    answers: [
      t('Maggi noodles', 'common', ['maggi', 'instant noodles', 'two-minute noodles']),
      t('Biscuits', 'common', ['parle g', 'marie biscuit', 'cookies', 'cream biscuit']),
      t('Chips', 'common', ['lays', 'kurkure', 'crisps', 'wafers']),
      t('Curd rice', 'common', ['perugu annam', 'yogurt rice', 'thayir sadam']),
      t('Avakaya rice', 'medium', ['pickle rice', 'avakaya', 'mango pickle rice']),
      t('Omelette', 'medium', ['egg omelette', 'eggs', 'omelet']),
      t('Leftover biryani from the fridge', 'medium', ['yesterday biryani', 'cold biryani', 'leftover biryani']),
      t('Ice cream', 'medium', ['kulfi', 'icecream', 'frozen dessert']),
      t('Hidden sweets from the box', 'medium', ['sweet box', 'laddu', 'sweets hidden somewhere']),
      t('Ordering food online', 'medium', ['swiggy', 'zomato', 'food delivery']),
      t('Peanuts', 'obscure', ['groundnuts', 'mixture', 'roasted peanuts']),
      t('Banana', 'obscure', ['bananas', 'fruit', 'the lone banana']),
    ],
  },
  {
    id: 'sleepy-class', locale: 'en-US', style: 'contextual',
    prompt: 'Signs you are falling asleep in class',
    answers: [
      t('Head slowly drooping forward', 'common', ['head drooping', 'head nodding', 'head falling']),
      t('Reading the same line five times', 'common', ['same line again', 'words not making sense', 'reading on loop']),
      t('Pen slipping from your fingers', 'common', ['pen dropping', 'pen falls', 'losing grip on pen']),
      t('Random doodles on the page', 'common', ['drawing in margins', 'scribbling', 'doodle appearing']),
      t('Snapping awake with a jerk', 'medium', ['sudden head snap', 'jerk awake', 'hypnic jerk', 'startled awake']),
      t('Handwriting turning into a scrawl', 'medium', ['unreadable notes', 'writing going messy', 'notes illegible']),
      t('Eyes blinking slower and slower', 'medium', ['heavy eyelids', 'eyes closing', 'slow blinks']),
      t("Teacher's voice fading into background", 'medium', ['not hearing teacher', 'muffled voice', 'voice becoming distant']),
      t('Propping chin on hand', 'obscure', ['elbow on desk', 'head in hands', 'chin on palm']),
      t('Brief dream before snapping back', 'obscure', ['micro sleep', 'quick dream', 'dream for a second']),
    ],
  },
  {
    id: 'auto-ride', locale: 'en-US', style: 'contextual',
    prompt: 'Things that happen on an auto-rickshaw ride',
    answers: [
      t('Haggling over the fare', 'common', ['bargaining', 'negotiating the rate', 'meter or fixed', 'fixing the price']),
      t('Wind blasting through the open sides', 'common', ['hair flying', 'breeze through open sides', 'wind in your face']),
      t('Shortcut through a narrow lane', 'common', ['gully shortcut', 'small lane detour', 'tiny road shortcut']),
      t('Hanging on around a sharp turn', 'medium', ['holding on for dear life', 'sudden sharp turn', 'sliding on the seat']),
      t('Driver on a call with one hand on the wheel', 'medium', ['driver phoning', 'one-handed driving', 'driver on phone']),
      t('Dangerous overtake of a bus', 'medium', ['risky pass', 'cutting in front of bus', 'overtaking dangerously']),
      t('Petrol fume smell', 'medium', ['exhaust smell', 'pollution smell', 'diesel fumes']),
      t('No exact change for the fare', 'medium', ['no change', 'exact change problem', 'driver says no change']),
      t('Sudden random stop in traffic', 'obscure', ['engine stall', 'random stop', 'stopping mid road']),
      t('Getting overcharged and arguing', 'obscure', ['extra charge', 'arguing the fare', 'ripped off on price']),
      t('Three people squeezed in a two-seater', 'obscure', ['extra passenger', 'shared auto', 'crammed auto']),
    ],
  },
];

// ─── Classic boards (category listing) ───────────────────────────────────────

const classic = [
  {
    id: 'nye-party', locale: 'en-US', style: 'classic',
    prompt: "Things you'd find at a New Year's Eve party",
    answers: [
      t('Champagne', 'common', ['bubbly', 'sparkling wine', 'prosecco', 'cava']),
      t('Fireworks', 'common', ['firecrackers', 'pyrotechnics']),
      t('Countdown', 'common', ['counting down', 'ten nine eight']),
      t('Confetti', 'common', ['streamers']),
      t('Midnight kiss', 'medium', ["new year's kiss", 'kiss at midnight']),
      t('Ball drop', 'medium', ['times square ball', 'dropping the ball']),
      t('Noisemakers', 'medium', ['party horns', 'horns', 'kazoos', 'party blowers']),
      t('Resolutions', 'medium', ["new year's resolutions", 'goals for the year']),
      t('Party hats', 'medium', ['paper hats', 'tiaras', 'crowns']),
      t('Auld Lang Syne', 'obscure', ['the new year song', 'should old acquaintance']),
      t('Sparklers', 'obscure'),
      t('Twelve grapes', 'obscure', ['lucky grapes', 'eating grapes at midnight']),
    ],
  },
  {
    id: 'kitchen', locale: 'en-US', style: 'classic',
    prompt: 'Things in a kitchen',
    answers: [
      t('Refrigerator', 'common', ['fridge', 'freezer']),
      t('Stove', 'common', ['oven', 'range', 'cooktop', 'burners']),
      t('Sink', 'common', ['faucet', 'tap']),
      t('Microwave', 'common'),
      t('Dishwasher', 'medium'),
      t('Toaster', 'medium', ['toaster oven']),
      t('Cutting board', 'medium', ['chopping board']),
      t('Knife block', 'medium', ['knives', "chef's knife"]),
      t('Spatula', 'medium', ['flipper', 'turner']),
      t('Colander', 'obscure', ['strainer', 'sieve']),
      t('Spice rack', 'obscure', ['spices', 'seasonings']),
      t('Oven mitts', 'obscure', ['pot holders', 'oven gloves']),
    ],
  },
  {
    id: 'beach-day', locale: 'en-US', style: 'classic',
    prompt: 'Things you bring or see on a beach day',
    answers: [
      t('Sunscreen', 'common', ['sunblock', 'spf', 'suntan lotion']),
      t('Towel', 'common', ['beach towel']),
      t('Umbrella', 'common', ['parasol', 'beach umbrella']),
      t('Sunglasses', 'common', ['shades']),
      t('Swimsuit', 'medium', ['bathing suit', 'swim trunks', 'bikini']),
      t('Cooler', 'medium', ['ice chest']),
      t('Sandcastle', 'medium', ['sand castle', 'bucket and spade']),
      t('Flip-flops', 'medium', ['sandals', 'thongs']),
      t('Frisbee', 'medium', ['flying disc']),
      t('Seashells', 'obscure', ['shells']),
      t('Boogie board', 'obscure', ['bodyboard']),
      t('Lifeguard', 'obscure', ['lifeguard tower']),
    ],
  },
  {
    id: 'late-for-work', locale: 'en-US', style: 'classic',
    prompt: 'Reasons you were late for work',
    answers: [
      t('Traffic', 'common', ['traffic jam', 'rush hour']),
      t('Overslept', 'common', ['slept in', "alarm didn't go off", 'hit snooze']),
      t('Car trouble', 'common', ['flat tire', "car wouldn't start", 'dead battery']),
      t('Train or bus delay', 'medium', ['missed the bus', 'train was late', 'public transport']),
      t('Kids', 'medium', ['school drop-off', 'the kids']),
      t('Lost keys', 'medium', ["couldn't find my keys", 'keys']),
      t('Bad weather', 'medium', ['snow', 'rain', 'storm']),
      t('Coffee run', 'obscure', ['coffee line', 'getting coffee']),
      t('Appointment', 'obscure', ['doctor', 'dentist']),
      t('Pet emergency', 'obscure', ['the dog', 'vet']),
    ],
  },
  {
    id: 'birthday-party', locale: 'en-US', style: 'classic',
    prompt: 'Things at a birthday party',
    answers: [
      t('Cake', 'common', ['birthday cake']),
      t('Candles', 'common', ['candle']),
      t('Balloons', 'common', ['balloon']),
      t('Gifts', 'common', ['presents', 'gift', 'present']),
      t('Friends', 'common', ['guests', 'classmates']),
      t('Birthday song', 'medium', ['happy birthday song', 'happy birthday']),
      t('Party hats', 'medium', ['caps', 'birthday cap', 'party cap']),
      t('Return gifts', 'medium', ['return gift']),
      t('Chocolates', 'medium', ['chocolate', 'toffees']),
      t('Decorations', 'medium', ['streamers', 'ribbons', 'decoration']),
      t('Games', 'medium', ['party games', 'musical chairs']),
      t('Cake on the face', 'obscure', ['cake smash', 'face full of cake']),
      t('Photos', 'obscure', ['camera', 'selfies', 'photographs']),
    ],
  },
  {
    id: 'monsoon', locale: 'en-US', style: 'classic',
    prompt: 'Things you see in the monsoon',
    answers: [
      t('Umbrella', 'common', ['umbrellas']),
      t('Raincoat', 'common', ['rain coat']),
      t('Puddles', 'common', ['puddle', 'mud', 'muddy water']),
      t('Paper boats', 'medium', ['paper boat']),
      t('Thunder', 'medium'),
      t('Lightning', 'medium', ['lighting']),
      t('Frogs', 'medium', ['frog']),
      t('Rainbow', 'medium'),
      t('Dark clouds', 'medium', ['clouds', 'cloud']),
      t('Hot bajji', 'obscure', ['bajji', 'pakoda', 'pakora', 'mirchi bajji', 'pakodi']),
      t('Roasted corn', 'obscure', ['bhutta', 'corn']),
      t('Rain holiday', 'obscure', ['holiday', 'school holiday']),
      t('Cold and cough', 'obscure', ['cold', 'cough', 'sneezing']),
    ],
  },
  {
    id: 'street-food', locale: 'en-US', style: 'classic',
    prompt: 'Street food you can never say no to',
    answers: [
      t('Pani puri', 'common', ['gol gappa', 'golgappa', 'puchka', 'gupchup', 'pani poori']),
      t('Samosa', 'common', ['samosas']),
      t('Mirchi bajji', 'common', ['bajji', 'mirchi bhaji', 'chilli bajji']),
      t('Pav bhaji', 'common'),
      t('Bhel puri', 'medium', ['bhel', 'churumuri']),
      t('Chaat', 'medium', ['dahi puri', 'papdi chaat', 'masala puri']),
      t('Vada pav', 'medium', ['vada pao']),
      t('Momos', 'medium', ['momo']),
      t('Jalebi', 'medium', ['jilebi', 'jalebis']),
      t('Roasted corn', 'medium', ['bhutta', 'corn', 'corn on the cob']),
      t('Kulfi', 'obscure', ['ice cream', 'kulfi ice']),
      t('Sugarcane juice', 'obscure', ['ganne ka juice', 'cheruku rasam']),
      t('Egg puffs', 'obscure', ['puffs', 'egg puff', 'veg puff', 'bakery puffs']),
    ],
  },
];

export default [...contextual, ...classic];
