// Telugu topics for Andhra and Telangana players, written natively in Telugu (not translated).
// gloss: short English meaning, used only to help the matcher; players never see it.
// difficulty: common = 1 pt, medium = 2 pts, obscure = 3 pts (the less obvious, funnier answers).
// Boards are meant to be fun and relatable, not a knowledge test.
// style:'contextual'  — situations/behaviours; players describe rather than name; Jev needed for many guesses.
// style:'classic'     — category-listing boards; local match handles most guesses.

const t = (text, difficulty, aliases = [], gloss = '') => ({ key: text, text, difficulty, aliases, gloss });

export default [
  // ─── Classic boards ──────────────────────────────────────────────────────────
  {
    id: 'sankranti', locale: 'te-IN', style: 'classic',
    prompt: 'సంక్రాంతి పండుగలో కనిపించేవి',
    promptGloss: 'Things you see during the Sankranti festival',
    answers: [
      t('గాలిపటాలు', 'common', ['గాలిపటం', 'పతంగులు', 'పతంగి', 'kites', 'kite', 'galipatalu'], 'kites'),
      t('ముగ్గులు', 'common', ['ముగ్గు', 'రంగోలి', 'rangoli', 'muggulu', 'muggu'], 'rangoli floor patterns'),
      t('భోగి మంటలు', 'common', ['భోగి మంట', 'మంటలు', 'bonfire', 'bhogi manta'], 'Bhogi bonfire'),
      t('కొత్త బట్టలు', 'common', ['కొత్త దుస్తులు', 'new clothes', 'kotha battalu'], 'new clothes'),
      t('పొంగలి', 'medium', ['పొంగల్', 'చక్కెర పొంగలి', 'pongal', 'pongali'], 'pongal, sweet rice dish'),
      t('గంగిరెద్దులు', 'medium', ['గంగిరెద్దు', 'gangireddulu', 'gangireddu'], 'decorated performing bulls'),
      t('హరిదాసులు', 'medium', ['హరిదాసు', 'haridasu', 'haridasulu'], 'Haridasu devotional singers'),
      t('అరిసెలు', 'medium', ['అరిసె', 'ariselu', 'arise'], 'ariselu, rice and jaggery sweet'),
      t('చెరకు', 'medium', ['చెరుకు', 'చెరకు గడ', 'sugarcane', 'cheruku'], 'sugarcane'),
      t('కోడి పందేలు', 'obscure', ['కోడి పందెం', 'కోడిపందాలు', 'cockfight', 'kodi pandalu'], 'cockfights'),
      t('గొబ్బెమ్మలు', 'obscure', ['గొబ్బెమ్మ', 'gobbemmalu', 'gobbemma'], 'cow-dung mounds placed on rangoli'),
      t('భోగి పళ్ళు', 'obscure', ['భోగి పండ్లు', 'రేగి పళ్ళు', 'regi pallu', 'bhogi pallu'], 'jujube berries showered on children'),
    ],
  },
  {
    id: 'telugu-wedding', locale: 'te-IN', style: 'classic',
    prompt: 'తెలుగు పెళ్ళిలో కనిపించేవి',
    promptGloss: 'Things you see at a Telugu wedding',
    answers: [
      t('పెళ్ళికూతురు', 'common', ['వధువు', 'పెళ్లికూతురు', 'bride', 'pellikuthuru'], 'bride'),
      t('పెళ్ళికొడుకు', 'common', ['వరుడు', 'పెళ్లికొడుకు', 'groom', 'pellikoduku'], 'groom'),
      t('తాళి', 'common', ['మంగళసూత్రం', 'తాళిబొట్టు', 'mangalsutra', 'thali'], 'mangalsutra, sacred wedding necklace'),
      t('పందిరి', 'common', ['పెళ్ళి పందిరి', 'మండపం', 'pandiri', 'mandapam'], 'wedding canopy'),
      t('పెళ్ళి భోజనం', 'common', ['విందు', 'భోజనం', 'అరిటాకు భోజనం', 'feast', 'wedding lunch'], 'wedding feast'),
      t('మేళతాళాలు', 'medium', ['మేళం', 'సన్నాయి', 'nadaswaram', 'band'], 'nadaswaram and drums'),
      t('జీలకర్ర బెల్లం', 'medium', ['జీలకర్ర', 'jeelakarra bellam'], 'cumin and jaggery ritual'),
      t('తలంబ్రాలు', 'medium', ['talambralu'], 'couple showering rice on each other'),
      t('అక్షింతలు', 'medium', ['akshintalu', 'అక్షతలు'], 'turmeric rice blessings from guests'),
      t('కన్యాదానం', 'medium', ['kanyadanam', 'kanyadaan'], 'giving away the bride'),
      t('బాసికం', 'obscure', ['బాసికాలు', 'basikam'], 'ornament tied on the forehead of the couple'),
      t('అరుంధతి నక్షత్రం', 'obscure', ['అరుంధతి', 'arundhati'], 'showing the couple the Arundhati star'),
      t('మెట్టెలు', 'obscure', ['మట్టెలు', 'toe rings', 'mettelu'], 'toe rings'),
    ],
  },
  {
    id: 'chinnappati-atalu', locale: 'te-IN', style: 'classic',
    prompt: 'చిన్నప్పుడు ఆడుకున్న ఆటలు',
    promptGloss: 'Games we played as kids',
    answers: [
      t('క్రికెట్', 'common', ['cricket'], 'cricket'),
      t('కబడ్డీ', 'common', ['చెడుగుడు', 'kabaddi'], 'kabaddi'),
      t('ఖో ఖో', 'common', ['ఖోఖో', 'kho kho'], 'kho kho'),
      t('దాగుడు మూతలు', 'common', ['దాగుడుమూతలు', 'hide and seek', 'dagudu muthalu'], 'hide and seek'),
      t('గోళీలు', 'medium', ['గోలీలు', 'గోటీలు', 'marbles', 'golilu'], 'marbles'),
      t('బిళ్ళంగోడు', 'medium', ['గిల్లీ దండా', 'చిర్రగోనె', 'చిర్ర గోనె', 'gilli danda'], 'gilli-danda'),
      t('తొక్కుడు బిళ్ళ', 'medium', ['తొక్కుడుబిళ్ళ', 'hopscotch'], 'hopscotch'),
      t('అష్టా చెమ్మా', 'medium', ['అష్ట చెమ్మా', 'అష్టా చమ్మా', 'ashta chamma'], 'ashta chamma board game'),
      t('గాలిపటాలు', 'medium', ['గాలిపటం', 'పతంగి', 'kites'], 'flying kites'),
      t('బొంగరం', 'medium', ['బొంగరాలు', 'top', 'spinning top'], 'spinning top'),
      t('వామన గుంటలు', 'obscure', ['వామనగుంటలు', 'vamana guntalu'], 'pit-and-seed board game'),
      t('లూడో', 'obscure', ['పచ్చీసు', 'ludo', 'పాము నిచ్చెన', 'snakes and ladders'], 'ludo or snakes and ladders'),
      t('కోతి కొమ్మచ్చి', 'obscure', ['కోతికొమ్మచ్చి', 'చెట్లు ఎక్కడం', 'koti kommachi'], 'tree-climbing tag game'),
    ],
  },
  {
    id: 'varshakalam', locale: 'te-IN', style: 'classic',
    prompt: 'వర్షం పడుతుంటే కనిపించేవి',
    promptGloss: 'Things you see when it rains',
    answers: [
      t('గొడుగు', 'common', ['గొడుగులు', 'umbrella'], 'umbrella'),
      t('బురద', 'common', ['బురద నీళ్ళు', 'నీటి గుంటలు', 'mud', 'puddles'], 'mud and puddles'),
      t('కాగితం పడవలు', 'common', ['కాగితపు పడవ', 'పడవలు', 'paper boats'], 'paper boats'),
      t('రెయిన్ కోట్', 'common', ['రెయిన్‌కోట్', 'వాన కోటు', 'raincoat'], 'raincoat'),
      t('ఉరుములు', 'medium', ['ఉరుము', 'thunder'], 'thunder'),
      t('మెరుపులు', 'medium', ['మెరుపు', 'lightning'], 'lightning'),
      t('కప్పలు', 'medium', ['కప్ప', 'బెకబెక', 'frogs'], 'croaking frogs'),
      t('ఇంద్రధనుస్సు', 'medium', ['హరివిల్లు', 'rainbow'], 'rainbow'),
      t('మిర్చి బజ్జీలు', 'medium', ['బజ్జీలు', 'మిరపకాయ బజ్జీ', 'పకోడీ', 'పకోడీలు', 'mirchi bajji'], 'hot bajji and pakodi'),
      t('కాల్చిన మొక్కజొన్న', 'medium', ['మొక్కజొన్న', 'మొక్కజొన్న పొత్తులు', 'బుట్టా', 'corn'], 'roasted corn'),
      t('స్కూల్ సెలవు', 'obscure', ['సెలవు', 'వర్షం సెలవు', 'holiday'], 'rain holiday from school'),
      t('జలుబు', 'obscure', ['దగ్గు', 'తుమ్ములు', 'cold'], 'catching a cold'),
      t('కరెంట్ పోవడం', 'obscure', ['కరెంట్ పోయింది', 'కరెంట్ లేదు', 'power cut'], 'power cut'),
    ],
  },
  {
    id: 'vesavi-selavulu', locale: 'te-IN', style: 'classic',
    prompt: 'వేసవి సెలవుల్లో జరిగేవి',
    promptGloss: 'Things during summer holidays',
    answers: [
      t('మామిడి పళ్ళు', 'common', ['మామిడి పండు', 'మామిడి', 'బంగినపల్లి', 'రసాలు', 'mangoes'], 'mangoes'),
      t('అమ్మమ్మ ఊరు', 'common', ['అమ్మమ్మ ఇల్లు', 'నానమ్మ ఇల్లు', 'ఊరికి వెళ్ళడం', 'grandparents village'], "going to grandparents' village"),
      t('ఐస్ క్రీమ్', 'common', ['ఐస్‌క్రీమ్', 'పుల్ల ఐస్', 'కుల్ఫీ', 'ice cream'], 'ice cream and ice candy'),
      t('ఎండలు', 'common', ['ఎండ', 'వేడి', 'heat'], 'scorching sun'),
      t('క్రికెట్', 'common', ['cricket'], 'cricket all day'),
      t('పుచ్చకాయ', 'medium', ['watermelon'], 'watermelon'),
      t('తాటి ముంజలు', 'medium', ['ముంజలు', 'ice apple', 'munjalu'], 'ice apple'),
      t('చెరకు రసం', 'medium', ['చెరుకు రసం', 'sugarcane juice'], 'sugarcane juice'),
      t('ఈత', 'medium', ['ఈత కొట్టడం', 'బావిలో ఈత', 'swimming'], 'swimming'),
      t('మట్టి కుండ నీళ్ళు', 'medium', ['కుండ నీళ్ళు', 'కుండ', 'clay pot'], 'cool water from a clay pot'),
      t('సినిమాలు', 'medium', ['సినిమా', 'movies'], 'watching movies'),
      t('ఆవకాయ పెట్టడం', 'obscure', ['ఆవకాయ', 'ఊరగాయ పెట్టడం', 'pickle making'], 'making mango pickle at home'),
      t('మధ్యాహ్నం నిద్ర', 'obscure', ['మధ్యాహ్నం పడుకోవడం', 'afternoon nap'], 'forced afternoon nap'),
    ],
  },
  {
    id: 'ugadi', locale: 'te-IN', style: 'classic',
    prompt: 'ఉగాది పండుగలో ఉండేవి',
    promptGloss: 'Things at the Ugadi festival',
    answers: [
      t('ఉగాది పచ్చడి', 'common', ['పచ్చడి', 'ugadi pachadi'], 'six-taste Ugadi chutney'),
      t('మామిడి తోరణాలు', 'common', ['తోరణాలు', 'మామిడాకులు', 'mango leaves'], 'mango-leaf door garlands'),
      t('కొత్త బట్టలు', 'common', ['కొత్త డ్రెస్', 'new clothes'], 'new clothes'),
      t('పచ్చి మామిడికాయ', 'common', ['మామిడికాయ', 'పచ్చి మామిడి', 'raw mango'], 'raw mango'),
      t('బెల్లం', 'medium', ['jaggery'], 'jaggery'),
      t('వేప పువ్వు', 'medium', ['వేప పూత', 'వేపపువ్వు', 'వేప', 'neem flowers'], 'neem flowers'),
      t('చింతపండు', 'medium', ['చింత పండు', 'tamarind'], 'tamarind'),
      t('తలంటు స్నానం', 'medium', ['తలస్నానం', 'నూనె స్నానం', 'oil bath'], 'oil bath in the morning'),
      t('బొబ్బట్లు', 'medium', ['భక్ష్యాలు', 'పోళీలు', 'పోలెలు', 'bobbatlu', 'bakshalu'], 'bobbatlu sweet flatbread'),
      t('పంచాంగ శ్రవణం', 'medium', ['పంచాంగం', 'జాతకం', 'panchangam'], 'listening to the new-year almanac'),
      t('పచ్చడి తిని ముఖం చిట్లించడం', 'obscure', ['చేదు', 'ముఖం చిట్లించడం', 'చేదు ముఖం', 'bitter face'], 'pulling a face at the bitter chutney'),
      t('షడ్రుచులు', 'obscure', ['ఆరు రుచులు', 'six tastes'], 'six tastes'),
    ],
  },
  {
    id: 'bathukamma', locale: 'te-IN', style: 'classic',
    prompt: 'బతుకమ్మ పండుగలో కనిపించేవి',
    promptGloss: 'Things you see at Bathukamma',
    answers: [
      t('పూలు', 'common', ['పువ్వులు', 'flowers'], 'flowers'),
      t('బతుకమ్మ పాటలు', 'common', ['పాటలు', 'బతుకమ్మ పాట', 'songs'], 'Bathukamma songs'),
      t('చప్పట్లు', 'common', ['చప్పట్లు కొట్టడం', 'clapping'], 'clapping in a circle'),
      t('పట్టు చీరలు', 'common', ['చీరలు', 'పట్టు చీర', 'sarees'], 'silk sarees'),
      t('తంగేడు పూలు', 'medium', ['తంగేడు', 'tangedu'], 'tangedu flowers'),
      t('గునుగు పూలు', 'medium', ['గునుగు', 'gunugu'], 'gunugu flowers'),
      t('చెరువు', 'medium', ['కుంట', 'నిమజ్జనం', 'lake'], 'the lake where it is floated'),
      t('గౌరమ్మ', 'medium', ['పసుపు గౌరమ్మ', 'గౌరి', 'gauramma'], 'turmeric Gauramma on top'),
      t('తాంబాళం', 'medium', ['పళ్ళెం', 'plate'], 'big plate the flowers are stacked on'),
      t('సద్దులు', 'medium', ['ప్రసాదం', 'సత్తుపిండి', 'నైవేద్యం', 'prasadam'], 'festival food offerings'),
      t('డీజే పాటలు', 'obscure', ['డీజే', 'dj'], 'DJ songs'),
      t('సెల్ఫీలు', 'obscure', ['సెల్ఫీ', 'ఫోటోలు', 'selfies'], 'selfies with the Bathukamma'),
    ],
  },
  {
    id: 'deepavali', locale: 'te-IN', style: 'classic',
    prompt: 'దీపావళి పండుగలో కనిపించేవి',
    promptGloss: 'Things you see at Deepavali',
    answers: [
      t('టపాసులు', 'common', ['టపాకాయలు', 'బాణాసంచా', 'crackers'], 'crackers'),
      t('దీపాలు', 'common', ['ప్రమిదలు', 'దివ్వెలు', 'lamps', 'diyas'], 'lamps'),
      t('స్వీట్లు', 'common', ['మిఠాయిలు', 'sweets'], 'sweets'),
      t('కొత్త బట్టలు', 'common', ['కొత్త డ్రెస్', 'new clothes'], 'new clothes'),
      t('చిచ్చుబుడ్లు', 'medium', ['చిచ్చుబుడ్డి', 'flower pots'], 'flower-pot fireworks'),
      t('భూచక్రాలు', 'medium', ['భూచక్రం', 'chakri', 'ground chakkar'], 'ground spinners'),
      t('కాకరపువ్వొత్తులు', 'medium', ['కాకర పువ్వొత్తులు', 'కాకరపువ్వొత్తి', 'sparklers'], 'sparklers'),
      t('తారాజువ్వలు', 'medium', ['తారాజువ్వ', 'రాకెట్లు', 'రాకెట్', 'rockets'], 'rockets'),
      t('లక్ష్మీ బాంబులు', 'medium', ['బాంబులు', 'బాంబు', 'లక్ష్మీ బాంబు', 'bombs'], 'loud bombs'),
      t('భయపడే కుక్కలు', 'obscure', ['కుక్కలు', 'కుక్క భయం', 'scared dogs'], 'scared dogs hiding'),
      t('పొగ', 'obscure', ['పొగ వాసన', 'smoke'], 'smoke everywhere'),
      t('కాలిన వేళ్ళు', 'obscure', ['చేయి కాలడం', 'కాలిన చేయి', 'burnt finger'], 'burnt fingers'),
      t('తుస్సుమన్న టపాసు', 'obscure', ['తుస్సు', 'తుస్', 'పేలని బాంబు', 'dud cracker'], 'a dud cracker that fizzles out'),
    ],
  },

  // ─── Contextual boards ────────────────────────────────────────────────────────
  {
    id: 'vantillu', locale: 'te-IN', style: 'contextual',
    prompt: 'ఉదయం అమ్మ వంట చేసేటప్పుడు జరిగేవి',
    promptGloss: 'Things that happen while mom cooks in the morning',
    answers: [
      t('కూకర్ విజిల్ నిద్ర లేపడం', 'common', ['కూకర్ శబ్దం', 'విజిల్ వినిపించడం', 'cooker sound', 'whistle woke me up'], 'pressure cooker whistle waking you up'),
      t('మిక్సీ శబ్దం ఇంట్లో నిండిపోవడం', 'common', ['మిక్సీ అరుపు', 'mixie noise', 'grinder sound'], 'the mixer grinder filling the house with noise'),
      t('వంట వాసన పక్కింటికీ వెళ్ళడం', 'common', ['వంట వాసన', 'cooking smell', 'smell of food'], 'the smell of cooking spreading to neighbours'),
      t('పొగడ్డ గ్యాస్ అయిపోవడం', 'common', ['గ్యాస్ అయిపోయింది', 'cylinder empty', 'gas ran out'], 'gas cylinder running out at the wrong moment'),
      t('అమ్మ పాటలు పాడుతూ వంట చేయడం', 'medium', ['పాటలు', 'songs while cooking', 'humming'], 'mom humming songs while cooking'),
      t('టిఫిన్ రెడీ కాకముందే హడావుడి', 'medium', ['రెడీ కాలేదు', 'tiffin not ready', 'hurrying for food'], 'rush before the tiffin is ready'),
      t('చిన్నప్పటి డబ్బాలో దాచిన స్వీట్లు కనుక్కోవడం', 'medium', ['స్వీట్లు దాచడం', 'hidden sweets found', 'secret sweet box'], 'discovering hidden sweets in an old tin'),
      t('మసాలా వాసనకి తుమ్ము వచ్చిన', 'medium', ['మసాలా', 'sneezing from spices', 'spice sneeze'], 'sneezing because of the spices'),
      t('కత్తిపీట మీద కూరగాయలు కోసే శబ్దం', 'medium', ['కూరగాయలు కోయడం', 'chopping sounds', 'vegetables cutting'], 'the rhythmic sound of chopping vegetables'),
      t('ఫ్రిజ్‌లో ఏముందో చూసి మళ్ళీ మూసేయడం', 'obscure', ['ఫ్రిజ్ తెరవడం', 'fridge check', 'opening fridge with hope'], 'opening the fridge then closing it with nothing'),
      t('అమ్మ చప్పుడు చేయకుండా పాత్రలు కడగడం', 'obscure', ['పాత్రలు కడగడం', 'washing vessels', 'dish washing'], 'quietly washing vessels without waking anyone'),
      t('పక్కింటి వాళ్ళ ఇడ్లీ వాసన', 'obscure', ['పక్కింటి వాసన', "neighbour's cooking smell", 'idli smell from next door'], "the neighbour's idli smell drifting over"),
    ],
  },
  {
    id: 'current-poyindi', locale: 'te-IN', style: 'contextual',
    prompt: 'కరెంట్ పోతే చేసేవి',
    promptGloss: 'Things you do when the power goes off',
    answers: [
      t('కొవ్వొత్తి', 'common', ['కొవ్వొత్తులు', 'క్యాండిల్', 'candle', 'kovvotti'], 'light a candle'),
      t('ఫోన్ టార్చ్', 'common', ['టార్చ్', 'టార్చ్ లైట్', 'ఫోన్ లైట్', 'torch', 'flashlight'], 'phone torch'),
      t('దోమలు', 'common', ['దోమ', 'దోమలు కుట్టడం', 'mosquitoes', 'domalu'], 'mosquitoes biting'),
      t('చెమటలు', 'common', ['చెమట', 'ఉక్కపోత', 'sweating', 'ఉక్క'], 'sweating in the heat'),
      t('విసనకర్ర', 'medium', ['విసురుకోవడం', 'పుస్తకంతో విసురుకోవడం', 'hand fan', 'visanakarra'], 'fanning yourself with a hand fan or book'),
      t('డాబా మీదకి వెళ్ళడం', 'medium', ['డాబా', 'మేడ మీద', 'బయట కూర్చోవడం', 'బాల్కనీ', 'terrace'], 'going to the terrace or sitting outside'),
      t('కరెంట్ ఆఫీస్‌కి ఫోన్', 'medium', ['కరెంట్ ఆఫీస్', 'లైన్‌మెన్', 'కంప్లైంట్', 'complaint', 'lineman'], 'calling the electricity office'),
      t('ఇన్వర్టర్', 'medium', ['యూపీఎస్', 'జనరేటర్', 'inverter', 'ups'], 'inverter'),
      t('ఛార్జింగ్ టెన్షన్', 'medium', ['ఛార్జింగ్', 'బ్యాటరీ అయిపోవడం', 'పవర్ బ్యాంక్', 'charging', 'phone battery'], 'worrying about the phone battery'),
      t('అంత్యాక్షరి', 'medium', ['పాటలు పాడటం', 'పాటలు', 'antakshari'], 'singing antakshari'),
      t('నిద్రపోవడం', 'medium', ['పడుకోవడం', 'నిద్ర', 'sleep'], 'going to sleep'),
      t('దెయ్యం కథలు', 'obscure', ['దెయ్యాల కథలు', 'భయం కథలు', 'ghost stories'], 'telling ghost stories'),
      t('పక్కింట్లో కరెంట్ ఉందా చూడటం', 'obscure', ['పక్కింట్లో కరెంట్', 'పక్కింటి వాళ్ళకి ఉందా', 'పక్కిల్లు', 'neighbours'], 'checking whether the neighbours have power'),
    ],
  },
  {
    id: 'homework-sakulu', locale: 'te-IN', style: 'contextual',
    prompt: 'హోంవర్క్ చేయకపోవడానికి సాకులు',
    promptGloss: 'Excuses for not doing homework',
    answers: [
      t('మర్చిపోయాను', 'common', ['మర్చిపోయా', 'మరిచిపోయాను', 'మరిచిపోయా', 'forgot'], 'I forgot'),
      t('బుక్ ఇంట్లో మర్చిపోయా', 'common', ['బుక్ ఇంట్లో ఉంది', 'నోట్స్ ఇంట్లో', 'నోట్‌బుక్ ఇంట్లో', 'left it at home'], 'left the notebook at home'),
      t('కరెంట్ లేదు', 'common', ['కరెంట్ పోయింది', 'కరెంట్ కట్', 'power cut', 'current poyindi'], 'power cut'),
      t('జ్వరం వచ్చింది', 'common', ['జ్వరం', 'ఒంట్లో బాలేదు', 'తలనొప్పి', 'కడుపు నొప్పి', 'fever'], 'I was sick'),
      t('చుట్టాలు వచ్చారు', 'common', ['చుట్టాలు', 'గెస్టులు', 'బంధువులు వచ్చారు', 'relatives came'], 'relatives came home'),
      t('కుక్క తినేసింది', 'medium', ['కుక్క చింపేసింది', 'కుక్క', 'dog ate it'], 'the dog ate it'),
      t('పెళ్ళికి వెళ్ళాం', 'medium', ['పెళ్ళి', 'ఫంక్షన్', 'ఫంక్షన్‌కి వెళ్ళాం', 'wedding'], 'went to a wedding'),
      t('తమ్ముడు చింపేశాడు', 'medium', ['చెల్లి చింపేసింది', 'తమ్ముడు', 'చింపేశారు', 'brother tore it'], 'little brother tore it'),
      t('హోంవర్క్ ఉందని తెలియదు', 'medium', ['తెలియదు', 'ఎవరూ చెప్పలేదు', 'నాకు తెలియదు', "didn't know"], "didn't know there was homework"),
      t('నిద్ర వచ్చేసింది', 'medium', ['నిద్రపోయా', 'నిద్ర', 'పడుకున్నా', 'fell asleep'], 'fell asleep'),
      t('మ్యాచ్ చూశా', 'obscure', ['క్రికెట్ మ్యాచ్', 'ఐపీఎల్', 'మ్యాచ్', 'ipl', 'cricket match'], 'was watching the cricket match'),
      t('వర్షంలో తడిసిపోయింది', 'obscure', ['తడిసిపోయింది', 'వర్షం', 'వాన', 'got wet'], 'it got wet in the rain'),
      t('చేశాను కానీ తేలేదు', 'obscure', ['చేశాను', 'చేశా కానీ మర్చిపోయా', 'did it but forgot'], 'did it but forgot to bring it'),
    ],
  },
  {
    id: 'chuttalu', locale: 'te-IN', style: 'contextual',
    prompt: 'ఇంటికి చుట్టాలు వస్తే జరిగేవి',
    promptGloss: 'What happens when relatives visit',
    answers: [
      t('కాఫీ టీలు', 'common', ['కాఫీ', 'టీ', 'చాయ్', 'tea', 'coffee'], 'tea and coffee'),
      t('స్వీట్లు', 'common', ['స్వీట్', 'మిఠాయిలు', 'sweets'], 'sweets'),
      t('ఇల్లు సర్దడం', 'common', ['ఇల్లు శుభ్రం', 'సర్దడం', 'క్లీనింగ్', 'cleaning'], 'tidying up the house'),
      t('మార్కులు అడగడం', 'common', ['మార్కులు ఎన్ని', 'మార్కులు', 'ఏం చదువుతున్నావ్', 'ఏ క్లాస్', 'marks'], 'asking about your marks'),
      t('ఎంత పెద్దయ్యావ్', 'medium', ['ఎంత ఎదిగావ్', 'ఎంత పొడుగయ్యావ్', 'పెద్దయ్యావ్', 'grown so tall'], '"look how tall you have grown"'),
      t('పాట పాడమనడం', 'medium', ['పాట పాడు', 'డాన్స్ చెయ్యి', 'పాట', 'sing a song'], 'being asked to sing or dance'),
      t('బిర్యానీ', 'medium', ['చికెన్', 'మటన్', 'స్పెషల్ వంట', 'biryani'], 'special food is cooked'),
      t('కజిన్స్ అల్లరి', 'medium', ['కజిన్స్', 'పిల్లల గొడవ', 'అల్లరి', 'cousins'], 'cousins making a racket'),
      t('టీవీ రిమోట్ గొడవ', 'medium', ['రిమోట్', 'టీవీ', 'సీరియల్', 'remote'], 'fighting over the TV remote'),
      t('ఫోటోలు', 'medium', ['సెల్ఫీ', 'సెల్ఫీలు', 'photos'], 'taking photos'),
      t('నేల మీద పడుకోవడం', 'obscure', ['చాప', 'పరుపులు', 'నేల మీద', 'sleep on the floor'], 'sleeping on the floor'),
      t('బంగారం కబుర్లు', 'obscure', ['బంగారం', 'నగలు', 'చీరలు', 'gold'], 'chatting about gold and sarees'),
      t('పెళ్ళి ఎప్పుడు', 'obscure', ['పెళ్ళి సంబంధాలు', 'సంబంధాలు', 'when is the wedding'], '"when are you getting married?"'),
    ],
  },
  {
    id: 'amma-matalu', locale: 'te-IN', style: 'contextual',
    prompt: 'అమ్మ ఎప్పుడూ అనే మాటలు',
    promptGloss: 'Things mom always says',
    answers: [
      t('చదువుకో', 'common', ['చదువుకోరా', 'చదువుకోవే', 'చదువు', 'study'], '"go and study"'),
      t('ఫోన్ పక్కన పెట్టు', 'common', ['ఫోన్', 'ఫోన్ ఆపు', 'ఎప్పుడూ ఫోనేనా', 'phone'], '"put the phone down"'),
      t('తిన్నావా', 'common', ['అన్నం తిన్నావా', 'తిను', 'అన్నం తిను', 'have you eaten'], '"did you eat?"'),
      t('లే లేట్ అయింది', 'common', ['లే', 'నిద్ర లే', 'త్వరగా లే', 'లేట్ అయింది', 'wake up'], '"wake up, it\'s late"'),
      t('జాగ్రత్త', 'common', ['జాగ్రత్తగా వెళ్ళు', 'జాగ్రత్తగా ఉండు', 'be careful'], '"be careful"'),
      t('పక్కింటి వాళ్ళని చూడు', 'medium', ['పక్కింటి అబ్బాయి', 'పక్కింటి అమ్మాయి', 'పక్కింటి పిల్లలు', 'compare'], '"look at the neighbour\'s kid"'),
      t('టీవీ కట్టేయ్', 'medium', ['టీవీ ఆపు', 'టీవీ', 'tv off'], '"switch off the TV"'),
      t('రూమ్ సర్దుకో', 'medium', ['గది సర్దు', 'సర్దుకో', 'రూమ్', 'clean your room'], '"clean your room"'),
      t('నాన్నకి చెప్తా', 'medium', ['నాన్నకు చెబుతా', 'నాన్న రానీ', 'నాన్న', 'tell your father'], '"I\'ll tell your father"'),
      t('నీళ్ళు తాగు', 'obscure', ['నీళ్ళు', 'drink water'], '"drink water"'),
      t('ఎవరితో మాట్లాడుతున్నావ్', 'obscure', ['ఎవరితో', 'ఎవరు', 'who are you talking to'], '"who are you talking to?"'),
      t('స్వెటర్ వేసుకో', 'obscure', ['స్వెటర్', 'చలి', 'sweater'], '"wear a sweater"'),
      t('ఎండలో తిరగకు', 'obscure', ['ఎండలో ఆడకు', 'ఎండ', 'లోపలికి రా', 'dont play in the sun'], '"don\'t roam in the sun"'),
    ],
  },
  {
    id: 'bus-prayanam', locale: 'te-IN', style: 'contextual',
    prompt: 'బస్సు ప్రయాణంలో జరిగేవి',
    promptGloss: 'Things that happen on a bus journey',
    answers: [
      t('కిటికీ సీటు', 'common', ['విండో సీటు', 'విండో సీట్', 'కిటికీ', 'window seat'], 'window seat'),
      t('కండక్టర్', 'common', ['టికెట్', 'టికెట్ టికెట్', 'conductor', 'ticket'], 'the conductor and tickets'),
      t('నిద్రపోవడం', 'common', ['నిద్ర', 'పక్కవాళ్ళ భుజం మీద నిద్ర', 'sleep'], 'falling asleep'),
      t('స్నాక్స్', 'common', ['చిప్స్', 'పల్లీలు', 'శనగలు', 'snacks'], 'snacks'),
      t('చిల్లర లేదు', 'medium', ['చిల్లర', 'చిల్లర ఇవ్వడు', 'change'], 'no change for the ticket'),
      t('సినిమా పాటలు', 'medium', ['పాటలు', 'హెడ్‌ఫోన్స్', 'songs'], 'film songs playing'),
      t('వాంతులు', 'medium', ['వాంతి', 'కడుపులో తిప్పడం', 'vomit'], 'motion sickness'),
      t('రష్', 'medium', ['నిలబడటం', 'జనం', 'ఫుల్ రష్', 'crowd'], 'crowded, standing all the way'),
      t('టీ బ్రేక్', 'medium', ['టిఫిన్ బ్రేక్', 'హోటల్ దగ్గర ఆపడం', 'దాబా', 'tea break'], 'stopping for tea'),
      t('కర్చీఫ్ వేసి సీటు', 'obscure', ['కర్చీఫ్', 'సీటు కోసం గొడవ', 'సీటు గొడవ', 'hanky on the seat'], 'throwing a hanky on a seat to reserve it'),
      t('గుంతల రోడ్', 'obscure', ['గుంతలు', 'జర్కులు', 'potholes'], 'bumpy potholed road'),
      t('హారన్', 'obscure', ['హారన్ శబ్దం', 'horn'], 'non-stop horn'),
      t('స్టాప్ మిస్', 'obscure', ['దిగాల్సిన స్టాప్', 'స్టాప్ దాటిపోయింది', 'missed my stop'], 'missing your stop'),
    ],
  },
  {
    id: 'ardharatri-akali', locale: 'te-IN', style: 'contextual',
    prompt: 'అర్ధరాత్రి ఆకలేస్తే తినేవి',
    promptGloss: 'Midnight snacks when hungry',
    answers: [
      t('మ్యాగీ', 'common', ['మ్యాగి', 'నూడుల్స్', 'maggi', 'noodles'], 'Maggi noodles'),
      t('బిస్కెట్లు', 'common', ['బిస్కెట్', 'పార్లే జీ', 'biscuits'], 'biscuits'),
      t('చిప్స్', 'common', ['లేస్', 'కుర్కురే', 'chips'], 'chips'),
      t('పెరుగన్నం', 'common', ['పెరుగు అన్నం', 'మజ్జిగ అన్నం', 'curd rice'], 'curd rice'),
      t('ఆవకాయ అన్నం', 'medium', ['ఆవకాయ', 'పచ్చడి అన్నం', 'ఊరగాయ', 'pickle rice'], 'rice with mango pickle'),
      t('ఆమ్లెట్', 'medium', ['గుడ్డు', 'ఎగ్', 'omelette'], 'omelette'),
      t('మిగిలిన బిర్యానీ', 'medium', ['బిర్యానీ', 'leftover biryani'], 'leftover biryani'),
      t('ఐస్ క్రీమ్', 'medium', ['ఐస్‌క్రీమ్', 'ఐస్‌క్రీం', 'ice cream'], 'ice cream'),
      t('చాక్లెట్', 'medium', ['చాక్లెట్లు', 'డెయిరీ మిల్క్', 'chocolate'], 'chocolate'),
      t('స్విగ్గీ ఆర్డర్', 'medium', ['స్విగ్గీ', 'జొమాటో', 'ఆన్‌లైన్ ఆర్డర్', 'swiggy', 'zomato'], 'ordering food online'),
      t('దాచిన స్వీట్లు', 'obscure', ['స్వీట్ డబ్బా', 'స్వీట్లు', 'లడ్డూ', 'sweets'], 'sweets hidden in the box'),
      t('పల్లీలు', 'obscure', ['వేరుశెనగ', 'మిక్చర్', 'peanuts'], 'peanuts or mixture'),
      t('అరటి పండు', 'obscure', ['అరటి పళ్ళు', 'అరటి', 'banana'], 'banana'),
    ],
  },
  {
    id: 'exam-mundu', locale: 'te-IN', style: 'contextual',
    prompt: 'పరీక్షల ముందు రాత్రి జరిగేవి',
    promptGloss: 'The night before exams',
    answers: [
      t('రాత్రంతా చదవడం', 'common', ['నైట్ అవుట్', 'రాత్రంతా', 'all night'], 'studying all night'),
      t('టీ కాఫీ', 'common', ['టీ', 'కాఫీ', 'tea', 'coffee'], 'tea and coffee to stay awake'),
      t('దేవుడికి దండం', 'common', ['దేవుడా', 'దండం', 'ప్రార్థన', 'pray'], 'praying to God'),
      t('నిద్ర ముంచుకొస్తుంది', 'common', ['నిద్ర వస్తుంది', 'నిద్ర', 'sleepy'], 'feeling sleepy'),
      t('సిలబస్ టెన్షన్', 'medium', ['సిలబస్', 'ఇంకా చాలా ఉంది', 'టెన్షన్', 'syllabus'], 'panic about the syllabus left'),
      t('ఇంపార్టెంట్ క్వశ్చన్స్', 'medium', ['ఇంపార్టెంట్ ప్రశ్నలు', 'ఇంపార్టెంట్', 'important questions'], 'hunting for important questions'),
      t('ఫ్రెండ్‌కి ఫోన్', 'medium', ['ఫ్రెండ్', 'వాట్సాప్ గ్రూప్', 'ఫ్రెండ్స్', 'call a friend'], 'calling a friend'),
      t('హాల్ టికెట్ వెతకడం', 'medium', ['హాల్ టికెట్', 'hall ticket'], 'searching for the hall ticket'),
      t('రివిజన్', 'medium', ['రివైజ్', 'మళ్ళీ చదవడం', 'revision'], 'revision'),
      t('అమ్మ ఇచ్చే బాదం పాలు', 'obscure', ['బాదం', 'బాదం పాలు', 'పాలు', 'almonds'], "mom's almonds and milk"),
      t('పెన్నులు రెడీ', 'obscure', ['పెన్నులు', 'పెన్ను', 'pens'], 'getting pens ready'),
      t('ఫోన్ దాచేయడం', 'obscure', ['ఫోన్ ఆఫ్', 'ఫోన్', 'phone off'], 'hiding the phone'),
    ],
  },
  {
    id: 'tiffins', locale: 'te-IN', style: 'contextual',
    prompt: 'స్కూల్‌కి లేట్ అయినప్పుడు జరిగేవి',
    promptGloss: 'Things that happen when you are late for school',
    answers: [
      t('యూనిఫాం ఇస్త్రీ చేయలేదు', 'common', ['ఇస్త్రీ లేదు', 'uniform not ironed', 'crumpled uniform'], 'uniform not ironed'),
      t('అల్పాహారం తినకుండా పరుగు తీయడం', 'common', ['తినకుండా వెళ్ళడం', 'skipped breakfast', 'no time to eat'], 'running without eating breakfast'),
      t('స్కూల్ బ్యాగ్ సర్దలేదు', 'common', ['బ్యాగ్ రెడీ లేదు', 'bag not packed', 'missing books'], 'school bag not packed the night before'),
      t('బస్సు మిస్ అవడం', 'common', ['బస్సు వెళ్ళిపోయింది', 'missed the bus', 'bus left without me'], 'missing the school bus'),
      t('అమ్మ కేకలు వేయడం', 'medium', ['అమ్మ అరవడం', 'mom shouting', 'scolding from mom'], 'mom shouting to hurry up'),
      t('బాత్రూమ్‌లో వరుస', 'medium', ['బాత్రూమ్ ఆగడం', 'bathroom queue', 'waiting for bathroom'], 'queue for the bathroom'),
      t('జుట్టు సర్దే సమయం లేదు', 'medium', ['జుట్టు దువ్వలేదు', 'hair not combed', 'no time to brush hair'], 'no time to comb hair'),
      t('హోంవర్క్ రాత్రంతా చేసి నిద్ర పోయడం', 'medium', ['రాత్రి చదివి లేట్ నిద్ర', 'slept late studying', 'studied all night'], 'slept late because of homework'),
      t('మిత్రుడికి ఫోన్ చేసి నోట్స్ అడగడం', 'obscure', ['friend notes', 'calling classmate', 'borrowing notes at last minute'], 'calling a friend for notes on the way'),
      t('గేటు దగ్గర మాస్టారు నిలబెట్టడం', 'obscure', ['గేటు వద్ద', 'caught at the gate', 'stopped at the gate'], 'being caught late at the school gate'),
      t('లేట్ ఎంట్రీ వల్ల క్లాస్ చూస్తుంది', 'obscure', ['అందరూ చూడడం', 'entire class staring', 'walk of shame to your seat'], 'entire class turning to stare as you walk in late'),
    ],
  },
  {
    id: 'galli-cricket', locale: 'te-IN', style: 'contextual',
    prompt: 'గల్లీ క్రికెట్‌లో జరిగేవి',
    promptGloss: 'Things that happen in gully cricket',
    answers: [
      t('బ్యాట్', 'common', ['ప్లాస్టిక్ బ్యాట్', 'bat'], 'bat'),
      t('టెన్నిస్ బాల్', 'common', ['బంతి', 'బాల్', 'ball'], 'tennis ball'),
      t('ఇటుకలే వికెట్లు', 'common', ['ఇటుకలు', 'వికెట్లు', 'రాళ్ళు', 'stumps'], 'bricks as stumps'),
      t('అద్దం పగలడం', 'common', ['అద్దం పగిలింది', 'కిటికీ అద్దం', 'broken window'], 'a window gets broken'),
      t('నేను ఔట్ కాదు', 'common', ['ఔట్ కాదు', 'గొడవ', 'గొడవలు', 'not out'], '"I am not out!" arguments'),
      t('బంతి పక్కింట్లో పడటం', 'medium', ['బంతి పోయింది', 'పక్కింట్లో బంతి', 'బాల్ పోయింది', 'lost ball'], "ball lands in the neighbour's house"),
      t('వన్ టిప్ వన్ హ్యాండ్', 'medium', ['వన్ టిప్', 'ఒంటి చేత్తో క్యాచ్', 'one tip one hand'], 'one-bounce one-hand catch rule'),
      t('ట్రయల్ బాల్', 'medium', ['ట్రయల్', 'trial ball'], 'trial ball'),
      t('బ్యాట్ ఎవరిదో వాళ్ళే కెప్టెన్', 'medium', ['బ్యాట్ ఓనర్', 'కెప్టెన్', 'bat owner'], 'whoever owns the bat is captain'),
      t('అమ్మ పిలవడం', 'medium', ['అమ్మ పిలుస్తోంది', 'ఇంటికి రా', 'mom calling'], 'mom calling you home'),
      t('వీధి కుక్కలు', 'obscure', ['కుక్కలు', 'dogs'], 'street dogs'),
      t('చీకటి పడటం', 'obscure', ['చీకటి', 'చీకటి పడింది', 'dark'], 'too dark to see'),
      t('లాస్ట్ మ్యాన్ బ్యాటింగ్', 'obscure', ['లాస్ట్ మ్యాన్', 'last man batting'], 'last man batting alone'),
    ],
  },
  {
    id: 'class-saradalu', locale: 'te-IN', style: 'contextual',
    prompt: 'క్లాస్‌రూమ్‌లో జరిగే సరదాలు',
    promptGloss: 'Fun things that happen in class',
    answers: [
      t('లాస్ట్ బెంచ్', 'common', ['వెనక బెంచ్', 'బ్యాక్ బెంచ్', 'last bench'], 'the last bench gang'),
      t('బెల్ కోసం ఎదురుచూపు', 'common', ['బెల్', 'లాంగ్ బెల్', 'లంచ్ బెల్', 'bell'], 'waiting for the bell'),
      t('క్లాసులో నిద్ర', 'common', ['నిద్ర', 'కునుకు', 'నిద్రపోవడం', 'sleeping in class'], 'dozing in class'),
      t('టీచర్ రాగానే సైలెంట్', 'common', ['సైలెంట్', 'నిశ్శబ్దం', 'టీచర్ వచ్చింది', 'silent'], 'going silent when the teacher walks in'),
      t('లంచ్ బాక్స్ షేరింగ్', 'medium', ['లంచ్ బాక్స్', 'టిఫిన్ షేరింగ్', 'lunch box'], 'sharing lunch boxes'),
      t('మానిటర్ పేర్లు రాయడం', 'medium', ['మానిటర్', 'మాట్లాడేవాళ్ళ పేర్లు', 'monitor'], 'monitor writing down names of talkers'),
      t('హోంవర్క్ కాపీ', 'medium', ['కాపీ', 'కాపీ కొట్టడం', 'copying homework'], 'copying homework'),
      t('చిట్టీలు పాస్ చేయడం', 'medium', ['చిట్టీలు', 'చిట్టీ', 'passing notes'], 'passing chits'),
      t('పీటీ పీరియడ్', 'medium', ['పీటీ', 'ఆటల పీరియడ్', 'games period', 'pt period'], 'PT period'),
      t('ప్రాక్సీ', 'obscure', ['ప్రాక్సీ అటెండెన్స్', 'proxy'], 'proxy attendance'),
      t('చాక్ పీస్ విసరడం', 'obscure', ['చాక్ పీస్', 'చాక్', 'chalk'], 'chalk piece flying across the room'),
      t('గోడ కుర్చీ', 'obscure', ['గోడకుర్చీ', 'పనిష్మెంట్', 'wall chair'], 'wall-chair punishment'),
      t('పేపర్ రాకెట్లు', 'obscure', ['పేపర్ రాకెట్', 'కాగితం రాకెట్', 'paper planes'], 'paper rockets'),
    ],
  },
];
